learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('',include(('learning_logs.urls','learning_logs'),namespace='learning_logs')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns=[
    # 主页
    url(r'^$',views.index,name='index'),
    # 显示所有的主题
    url(r'^topics/$',views.topics,name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),
]

users/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns =[
    url(r'^login/$',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$',views.register,name='register'),
]

django_bootstrap3/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic= models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text)>50:
            return self.text[:50] +"..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):

    class Meta:
        model=Topic
        fields = ['text']
        labels={'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields = ['text']
        labels={'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

django_bootstrap3/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from learning_logs.models import Topic,Entry
from .forms import TopicForm,EntryForm


# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context={'topics':topics}
    return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    # 校验是否为所属用户
    # if topic.owner!= request.user:
    #     raise Http404
    check_topic_owner(request,topic.owner)

    entries = topic.entry_set.order_by('-date_added')
    context= {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    if request.method!='POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic= form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    
    context = {'form':form}
    return render (request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    topic=Topic.objects.get(id=topic_id)
    if request.method!='POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.topic.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
        
    context={'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # if topic.owner != request.user:
    #     raise Http404
    check_topic_owner(request,topic.owner)

    if request.method!='POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    
    context={'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)


def check_topic_owner(request, user):
    if user is None or user!=request.user:
        raise Http404

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

# def login_sys(request):
#     username=request.POST.get('username')
#     password = request.POST.get('password')
#     user = authenticate(request,username=username,password=password)
#     if user is not None:
#         login(request,user)
#         return HttpResponseRedirect(reverse("learning_logs:index"))
    
#     return render(request,"users/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticate_user= authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
        
    context = {'form':form}
    return render(request,'users/register.html',context)

learning_logs/templates/learning_logs/base.html
{# Load the tag library #}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Learning Log</title>

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
</head>

<body>
    <!-- Static navbor -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="{%url 'learning_logs:index'%}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{%url 'learning_logs:topics'%}">Topics</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li> -->
            </ul>
            <ul class="navbar-nav justify-content-end">
                {%if user.is_authenticated%}
                <li class="nav-item"><a class="nav-link">Hello,{{user.username}}.</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'users:logout' %}">log out</a></li>
                {%else%}
                <li class="nav-item"><a class="nav-link" href="{%url 'users:register'%}">register</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'users:login'%}">log in</a></li>
                {%endif%}
            </ul>
            <!-- <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>
    </nav>

    <div role="main" class="container">
        <div class="page-header">
            {%block header%}{%endblock header%}
            <hr class="mb-4">
        </div>
        <div>{%block content%}{%endblock content%}</div>
    </div> <!-- /container -->
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{%extends 'learning_logs/base.html'%}
{%load bootstrap4%}

{%block header%}
<h3><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
{%endblock header%}

{%block content%} 
<p>Edit Entry:</p>
<form action="{%url 'learning_logs:edit_entry' entry.id%}" method="POST">
    {%csrf_token%}
    {%bootstrap_form form%}

    {%buttons%}
    <button type="submit" class="btn btn-primary">Add a entry</button>
    {%endbuttons%}
</form>
{%endblock content%}

learning_logs/templates/learning_logs/index.html
{%extends "learning_logs/base.html" %}

{%block header%}
<div class="jumbotron">
    <h1 class="display-4">Track your learning.</h1>
</div>
{%endblock header%}
{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{%extends 'learning_logs/base.html'%}
{%load bootstrap4%}

{%block header%}
<h3><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
{%endblock header%}

{%block content%} 
<p>Add a new Entry:</p>
<form action="{%url 'learning_logs:new_entry' topic.id %}" method='POST'>
    {%csrf_token%}
    {%bootstrap_form form%}

    {%buttons%}
    <button name='submit' class="btn btn-primary">add entry</button>
    {%endbuttons%}
</form>
{%endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{%extends 'learning_logs/base.html'%}
{%load bootstrap4%}

{%block header%}
<h2>Add a new topic:</h2>
{%endblock header%}

{%block content%}
<form action="{%url 'learning_logs:new_topic'%}" method="POST">
    {%csrf_token%}
    {%bootstrap_form form%}

    {%buttons%}
    <button name="submit" class="btn btn-primary">add topic</button>
    {%endbuttons%}
</form>
{%endblock content%}

learning_logs/templates/learning_logs/topic.html
{%extends 'learning_logs/base.html'%}

{%block header%}
<h2>{{topic}}</h2> 
{%endblock header%}

{%block content%}
<p><a href="{%url 'learning_logs:new_entry' topic.id %}">add new entry</a></p>
<ul>
    {%for entry in entries%}
    <div class="card mb-4">
        <div class="card-header">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        edit entry</a>
                </small>
            </h3>
        </div>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div> <!-- card -->
    {% empty %}
    There are no entries for this topic yet.
    {% endfor %}
</ul>

{%endblock content%}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{%block header%}
<h1>Topics</h1>
{%endblock header%}

{% block content %} 
<ul>
    {% for topic in  topics %}
    <li>
        <a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></li>
    {%empty%}
    <li>No topics have been added yet.</li>
    {%endfor%}
</ul>
<a href="{%url 'learning_logs:new_topic'%}">Add a new topic</a>
{% endblock content %}

users/templates/users/error.html
{%extends 'learning_logs/base.html'%}

{%block content%}
<p>登录失败，用户名或密码错误</p>
{%endblock content%}

users/templates/users/login.html
{%extends "learning_logs/base.html"%}
{%load bootstrap4%}

{%block header%}
<h2>Log in to your account.</h2>
{%endblock header%}

{%block content%}
{%if form.errors%}
<p>Your username and password didn't match.Please try again.</p>
{%endif%}
<form method="POST" action="{%url 'users:login'%}" />
{%csrf_token%}
{%bootstrap_form form%}

{%buttons%}
<button  name="submit" class="btn btn-primary">log in</button>
{%endbuttons%}
<input type="hidden" name="next" value="{%url 'learning_logs:index'%}"/>
</form>
{%endblock content%}

users/templates/users/register.html
{%extends 'learning_logs/base.html'%}

{%block content%}
<form action="{%url 'users:register' %}" method="POST">
{%csrf_token%}
{{form.as_p}}

<button name='submit'>register</button>
<input type='hidden' name='next' value="{%url 'learning_logs:index'%}" />
</form>
{%endblock content%}